var paths=[
          'bulletins/central-banking/1.xml',
          'bulletins/central-banking/2.xml',
          'bulletins/central-banking/3.xml',
          'bulletins/central-banking/4.xml',
          'bulletins/central-banking/5.xml',
          'bulletins/central-banking/6.xml',
          'bulletins/central-banking/7.xml',
          'bulletins/central-banking/8.xml',
          'bulletins/central-banking/9.xml',
          'bulletins/central-banking/10.xml',

          'bulletins/employment/1.xml',
          'bulletins/employment/2.xml',
          'bulletins/employment/3.xml',
          'bulletins/employment/4.xml',
          'bulletins/employment/5.xml',
          'bulletins/employment/6.xml',
          'bulletins/employment/7.xml',
          'bulletins/employment/8.xml',
          'bulletins/employment/9.xml',
          'bulletins/employment/10.xml',

          'bulletins/energy/1.xml',
          'bulletins/energy/2.xml',
          'bulletins/energy/3.xml',
          'bulletins/energy/4.xml',
          'bulletins/energy/5.xml',
          'bulletins/energy/6.xml',
          'bulletins/energy/7.xml',
          'bulletins/energy/8.xml',
          'bulletins/energy/9.xml',
          'bulletins/energy/10.xml',

          'bulletins/euro-debt-crisis/1.xml',
          'bulletins/euro-debt-crisis/2.xml',
          'bulletins/euro-debt-crisis/3.xml',
          'bulletins/euro-debt-crisis/4.xml',
          'bulletins/euro-debt-crisis/5.xml',
          'bulletins/euro-debt-crisis/6.xml',
          'bulletins/euro-debt-crisis/7.xml',
          'bulletins/euro-debt-crisis/8.xml',
          'bulletins/euro-debt-crisis/9.xml',
          'bulletins/euro-debt-crisis/10.xml',

          'bulletins/gold/1.xml',
          'bulletins/gold/2.xml',
          'bulletins/gold/3.xml',
          'bulletins/gold/4.xml',
          'bulletins/gold/5.xml',
          'bulletins/gold/6.xml',
          'bulletins/gold/7.xml',
          'bulletins/gold/8.xml',
          'bulletins/gold/9.xml',
          'bulletins/gold/10.xml',

          'bulletins/tech-bubble/1.xml',
          'bulletins/tech-bubble/2.xml',
          'bulletins/tech-bubble/3.xml',
          'bulletins/tech-bubble/4.xml',
          'bulletins/tech-bubble/5.xml',
          'bulletins/tech-bubble/6.xml',
          'bulletins/tech-bubble/7.xml',
          'bulletins/tech-bubble/8.xml',
          'bulletins/tech-bubble/9.xml',
          'bulletins/tech-bubble/10.xml',

          'bulletins/real-estate/1.xml',
          'bulletins/real-estate/2.xml',
          'bulletins/real-estate/3.xml',
          'bulletins/real-estate/4.xml',
          'bulletins/real-estate/5.xml',
          'bulletins/real-estate/6.xml',
          'bulletins/real-estate/7.xml',
          'bulletins/real-estate/8.xml',
          'bulletins/real-estate/9.xml',
          'bulletins/real-estate/10.xml'
        ];
var path='bulletins/central-banking/1.xml';//'short.xml';//'bulletins/central-banking/1.xml';
